name: node_http
description: HTTP client powered by Node I/O
version: 1.0.0-dev.1.0
homepage: https://github.com/pulyaevskiy/node-http
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev.19.0 <2.0.0'

dependencies:
  http: ^0.11.3
  node_io:
    git: https://github.com/pulyaevskiy/node-io.git

dev_dependencies:
  test: ^0.12.0
